dist: trusty
sudo: required
language: node_js
notifications:
  email: false
node_js:
  - "8"
cache: yarn
install:
  - yarn --frozen-lockfile
script:
  - set -e                     # fail fast
  # shutdown postgres instance ran by travis (WHY ITS EVEN THERE)
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - yarn test:coverage
  - yarn codecov
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # things needed to run ledger
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libgtk2.0-0
      - libxtst6
      - libnotify4
      - libgconf2-4
      - libgtk2.0-0:i386
      - libxtst6:i386
      - libnotify4:i386
      - libgconf2-4:i386
      - libnss3:i386
      - libasound2:i386
      - libxss1:i386
      - socat
      - libusb-1.0-0-dev
      - libudev-dev
