version: 2
jobs:
  install:
    docker:
      - image: krzkaczor/neufund-platform-base
    working_directory: /home/circleci/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          - v1-deps-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - ../.cache/Cypress
          key: v1-deps-cypress-{{ checksum "package.json" }}

  lint:
    docker:
      - image: krzkaczor/neufund-platform-base
    working_directory: /home/circleci/app

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          - v1-deps-
      - run: yarn prepare

      - run: yarn lint

  test:
    docker:
      - image: krzkaczor/neufund-platform-base
    working_directory: /home/circleci/app

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          - v1-deps-
      - run: yarn prepare

      - run: yarn test:browser-coverage && yarn test:node

  test-e2e:
    machine:
      enabled: true
      image: circleci/classic:edge
      docker_layer_caching: true

    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: ./.circleci/install-yarn.sh

      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          - v1-deps-
      - restore_cache:
          keys:
          - v1-deps-cypress-{{ checksum "package.json" }}
      - run: yarn prepare

      - run: source /opt/circleci/.nvm/nvm.sh && yarn test:e2e

  danger-ci:
    docker:
      - image: krzkaczor/neufund-platform-base
    working_directory: /home/circleci/app

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          - v1-deps-
      - run: yarn prepare

      - run: yarn storybook:screenshots
      - run: (export BASE_KEY=$(git rev-parse origin/master)  && export CURRENT_KEY=${CIRCLE_SHA1} && ./.circleci/vis-reg-run.sh)
      - run: yarn danger ci

workflows:
  version: 2

  mainflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - test-e2e:
          requires:
            - install
      - danger-ci:
          requires:
            - install
